### ISSUE TITLE
disableScroll options not work at  mobile device (real or emulated).

### ISSUE THREAD

**Issue by Ben07** [voronianski/react-swipe#101]
## Description
I check out demo from which your provide .But disableScroll option not work at  mobile device (real or emulated).

pc:         chrome 56
mobile:  ios 10.2.1

I found it:
```
line 296: if (options.disableScroll) event.preventDefault();  
```
modify to
```
if (options.disableScroll) return;
```
then it works,how about it?

## Demo link
[Demo](http://voronianski.github.io/react-swipe/demo/)

**Comment by agudulin** [comment]
Hi, @Ben07.

I've just tried the demo with `disableScroll` option turned on, it seems to be working:
http://voronianski.github.io/react-swipe/demo/?continuous=true&disableScroll=true

**Comment by Ben07** [comment]
Hi, @agudulin .
You set the `disableScroll` to `true` mean that I can't scroll pages by my finger.right?But actually I can do it in my mobile phone and chrome emulated.

**Comment by mallikvarma** [comment]
@Ben07  Yes, I too have this problem. even after setting disableScroll = true,  I am still able to slide using my fingures

**Comment by Ben07** [comment]
@mallikvarma Yep,so I add `if (options.disableScroll) return;` in move function.that works for me well.
[Source](https://github.com/Ben07/swipe-js-iso/blob/master/swipe.js#L296)

**Comment by voronianski** [comment]
@Ben07 closing as not related to this package. Please open PR for swipe.js to fix this if you are up to it. Thanks!
