### ISSUE TITLE
what i should do with the arguments of callback?

### ISSUE THREAD

**Issue by GodEngine** [voronianski/react-swipe#103]
after slide,i need the arguments(eq: 1 or 2 ...) of callback, but within the callback,i can't get the reffer of reactSwipe.Because this reffer to swiperOptions,the arguments which as the props of reactSwipe.

how can i get the reactSwipe in callback or transitionEnd, waitting for your answer...

thanks so mach

**Comment by voronianski** [comment]
@GodEngine use arrow functions in callback (https://github.com/voronianski/swipe-js-iso#config-options)

```
<ReactSwipe
  swipeOptions={{callback: (i) => {
    console.log(this); // refers to component
    console.log(i); // index
  }}}
/>
```
