### ISSUE TITLE
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

### ISSUE THREAD

**Issue by Zboule** [voronianski/react-swipe#106]
## Description

With react and typescript 2.2.2
Do you have any info ?

**Comment by andersekdahl** [comment]
It's because `react-swipe` imports `PropTypes` from the `react` package which has been deprectated in 15.5.0.

It should instead import the `prop-types` package.

**Comment by voronianski** [comment]
@jordaneCure @andersekdahl fixed, new version is `5.0.7`
