### ISSUE TITLE
Pin react dependency

### ISSUE THREAD

**Issue by amoskyler** [voronianski/react-swipe#11]
This should probably be pinned to a specific version of react. I just had some problems with it because it's pulling down 0.13 instead of 0.12.

https://github.com/jed/react-swipe/blob/gh-pages/package.json#L29

**Comment by voronianski** [comment]
Updated:

> starting from version `2.1.0` component depends on React `0.13.x`, latest version which depends on React `0.12.x` is `2.0.11`.
