### ISSUE TITLE
error in react 15.5.4

### ISSUE THREAD

**Issue by stefaniepei** [voronianski/react-swipe#110]
## Description
**package.json**
`
"react": "^15.5.4",
"react-dom": "^15.5.4",
"react-swipe": "^5.0.8",
"swipe-js-iso": "^2.0.3",
`
`<ReactSwipe></ReactSwipe>`

It doesn't work!
Error:Error: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).
when remove `<ReactSwipe></ReactSwipe>`,It's OK!

* you can use this link as a boilerplate - 
http://esnextb.in/?gist=8d9bf6bf17a4a3f779485e4baa6c3f26

**Comment by morajabi** [comment]
I think my latest pull request #108 will fix this if @voronianski check it out or add me as a contributor in the case he doesn't have enough time.

**Comment by voronianski** [comment]
fixed in `5.1.0`

**Comment by morajabi** [comment]
Great!
