### ISSUE TITLE
Swiping to much to left slows down swipe and render is slow

### ISSUE THREAD

**Issue by kgstefan88** [voronianski/react-swipe#113]
Hi, I have 50 elements in my carousel.
I noticed while fast swiping from right to left, after 15-20 items app slows down and sometimes it doesn't render whole item or no item at all. I can go back and swipe from left to right without problems (10 minutes of swiping without issues)

Carousel is continuous.

Any idea why it's breaking?

Thanks.

**Comment by voronianski** [comment]
This possible issue is related to Swipe.js itself (https://github.com/voronianski/swipe-js-iso which is just a port of https://github.com/thebird/Swipe).
