### ISSUE TITLE
 calculating width wrong

### ISSUE THREAD

**Issue by CodeLittlePrince** [voronianski/react-swipe#115]
The react's version is 15.6.1
The bug:
The width of Simulator screen is 375px, but react-swipe's per div's width is 359px.
And on my iPhone's safari, it will change to be correct after I move page up or down.

**Comment by voronianski** [comment]
This possible issue is related to Swipe.js itself (https://github.com/voronianski/swipe-js-iso which is just a port of https://github.com/thebird/Swipe).

**Comment by oskarer** [comment]
I had a similar problem, was able to solve it by setting width 100% on the react swipe container; here: https://github.com/voronianski/react-swipe/blob/gh-pages/src/reactSwipe.js#L32.

**Comment by sergiocloud** [comment]
For fix this you have to set `width: 100vw` in all styles (container, wrapper and child)

**Comment by oskarer** [comment]
> For fix this you have to set `width: 100vw` in all styles (container, wrapper and child)

Bear in mind that this only works if your swipe container takes up the full width of the screen, which is not always the case.

**Comment by robwierzbowski** [comment]
This feels like it might be related to the component calculating the width of the container and applying it to slides before CSS is applied. I see it calculating the width as the full screen width (1440) on my app, then calculating the correct size if I change the browser window after CSS is applied (taking into account CSS paddings, etc.).

**Comment by robwierzbowski** [comment]
Since this issue isn't fixed, I don't think it should be closed.
