### ISSUE TITLE
Use of the "key" property isn't the best solution for re-rendering

### ISSUE THREAD

**Issue by rhavenz** [voronianski/react-swipe#121]
When the key property change React will just unmount the component and mount a new one (childs included). In some case this isn't ideal.

Demo: https://codesandbox.io/s/ykl811jm7z (open the console)

**Comment by dzek69** [comment]
@rhavenz you forgot about documenting this thing in README.md :) please add, as this may be useful for people that doesn't read source code of used components too

**Comment by rhavenz** [comment]
@dzek69 You right... I will make a PR to update the README soon. 

Thank you.

FYI the version 5.1.0 doesn't include #122

**Comment by dzek69** [comment]
After second thought.
Why use a new prop? Component already knows about children count.

```javascript
const length = props.children && (props.children.length || 1);
const prevLength = prevProps.children && (prevProps.children.length || 1);
if (length !== prevLength) {
  // update
}
```

props.children may be not an object when no children is given, may be an object when single child is given or an array when multiple are given - this should cover all cases

**Comment by voronianski** [comment]
new version is `5.1.1` is available now
