### ISSUE TITLE
Weird behavior in Safari on continuous mode

### ISSUE THREAD

**Issue by FranciscoG** [voronianski/react-swipe#123]
## Description
on Safari I'm having this weird issue on continuous mode.  The slides are not transitioning seamlessly.  The current slide goes left off screen showing the background, then the incoming slide just appears.  

**Desktop**
Mac (10.12.6)  Safari (11.0) 

**Mobile**
_viewable using iOS simulator - iPhone 7, iOS 11_
iOS Webview (Cordova) <-- the issue is occurring here as well
iOS Safari  <-- however, I do not see the issue here.  

## Demo link
I tried matching my project setup as best as I could.  
https://codepen.io/FranciscoG/pen/bovyZR?editors=0100

**Comment by khw1031** [comment]
I have this issue too after updating iOS to 11.1

**Comment by alexlemons** [comment]
I am also having this issue.

**Comment by voronianski** [comment]
This possible issue is related to Swipe.js itself (https://github.com/voronianski/swipe-js-iso which is just a port of https://github.com/thebird/Swipe).

**Comment by VBagmut** [comment]
Issue is still not solved! I'm having the same behavior on Simulator iPhone XR and real iPhone too. Why are you closed it?
