### ISSUE TITLE
Swipe options are not updated

### ISSUE THREAD

**Issue by rcastill** [voronianski/react-swipe#125]
I'm setting `swipeOptions.disableScroll` depending on my component's state. Thing is, only initial config is used: if I start with `disableScroll=true` then the `ReactSwipe` component won't scroll (as expected) but can't change it's behavior afterwards and vice versa.

Is this a known issue? or not an issue at all?

**Comment by dzek69** [comment]
Yep, this component is not updating options.
According to this: https://github.com/voronianski/react-swipe/issues/121
Changing `key` will force component to re-mount, which will "update" options - but that's just workaround.

A fix needs to be prepared to update options when needed.

**Comment by voronianski** [comment]
you can use available methods on Swipe.js instance -
e.g. `disableScrolling` method added in latest Swipe.js version (https://github.com/voronianski/swipe-js-iso#swipe-api)

**Comment by dzek69** [comment]
This is what react wrapper library should take care of. It should hide what's underneath and expose "react way" of doing stuff.

Exposing child library instance sometimes may be useful of course, but in general we should use it only as a last resort, just like using "refs" in react.

**Comment by voronianski** [comment]
@dzek69 yeah, I will think about making comparisons of `props.swipeOptions`...

**Comment by voronianski** [comment]
@dzek69 fixed in latest version
