### ISSUE TITLE
ReactSwipe component does not proxy Swipe API setup() method

### ISSUE THREAD

**Issue by ahryhorieva** [voronianski/react-swipe#127]
Swipe slider is resized only when 'resize' event is fired. When its parent component's width changes due to some other reason, slider width remains the same.

Swipe exposes `setup()` method that can be used to manually trigger slider resizing (without the need to force ReactSwipe component to re-render). Although it's not listed in Swipe docs, it would be useful to have this method available in ReactSwipe component.

**Comment by voronianski** [comment]
@anna-hryhorieva you can access by making ref to component it like - `this.swipeComponent.swipe.setup()`
