### ISSUE TITLE
Wierd behaviour when less than 4 slides

### ISSUE THREAD

**Issue by krisal** [voronianski/react-swipe#129]
## Description
When I got a carousel with lets say 4 items it works like a charm. But as soon as I add an carousel with 2 items the component duplicates them, visually tho it's looking good but the callback don't work properly.

`callback = (index) => { index === 3 }` _(but there's only 2 in the swiper)_

Is this something that is solved or are there any nice solution for this case? Because right now I'm using an ugly if statement and it solves the problem for now.

Thanks!

**Comment by aprilbriz** [comment]
I had a same problem.
I figured out that there's a "special case" in swipe-js-iso. (I donno why)
https://github.com/voronianski/swipe-js-iso/blob/master/swipe.js#L52
So I modified my callback only when the length of children is 2.

**Comment by aprilbriz** [comment]
I think swipe-js-iso should return right index.

**Comment by ornicorn** [comment]
I have same issue too. Do you have any update for this?

**Comment by krisal** [comment]
I haven't have the time to try @springBriz comment. Will get back to you asap.

**Comment by lyon007** [comment]
@springBriz Did you solve this problem?

**Comment by strongcode9527** [comment]
I have same issue too.But I think the author may not fix this bug, because this component has not been updated for a long time.

**Comment by konrad147** [comment]
I have the same issue. I've found a partial solution. If you don't need continous slider you can set 'continues: false` and then swipe works as expected for 2 items.

**Comment by voronianski** [comment]
fixed in Swipe.js - https://github.com/voronianski/swipe-js-iso/commit/7370415ffee049c2a980f86ec5ceb28db7c056c6
