### ISSUE TITLE
Isn't possible to map a component directly

### ISSUE THREAD

**Issue by jonasantonelli** [voronianski/react-swipe#130]
## Description
I can't to render a Component directly.

For example:

`
 <ReactSwipe>
                { array.map(() => <Component />) }
</ReactSwipe>
`
## Demo link

* you can use this link as a boilerplate - 
http://esnextb.in/?gist=8d9bf6bf17a4a3f779485e4baa6c3f26

**Comment by sq9950** [comment]
`
<ReactSwipe>
  {
    array.map(
      () => <div><Component /></div>
    )
  }
</ReactSwipe>
`

**Comment by sq9950** [comment]
`
<ReactSwipe>
  {
    array.map(
      () => <div><Component /></div>
    )
  }
</ReactSwipe>
`

**Comment by mqliutie** [comment]
There  the `Component`  must be wrapped by `some element`. 

Otherwise it won't work

```
//not working
<ReactSwipe> { array.map( () => <Component /> ) } </ReactSwipe>
```
