### ISSUE TITLE
children number display error

### ISSUE THREAD

**Issue by bazingaedward** [voronianski/react-swipe#132]
## 
when the children number of <ReactSwipe> equals 2, the result children will double to four.like below:

## before

`
<ReactSwipe >
  {[
      <div data-index=0>one</div>,
      <div data-index=1>two</div>
]}
</ReactSwipe >
`

## after render
`
<ReactSwipe >
      <div data-index=0>one</div>
      <div data-index=1>two</div>
      <div data-index=2>one</div>,
      <div data-index=3>two</div>
</ReactSwipe >
`

**Comment by voronianski** [comment]
fixed in latest Swipe.js version, upgrade please
