### ISSUE TITLE
Unable to swipe iframes

### ISSUE THREAD

**Issue by ankit-casaone** [voronianski/react-swipe#133]
Hello team

I am using react-swipe to display Yelp reviews on our website. When I embed the Yelp reviews to form a carousel using the react-swipe, I am unable to swipe among the reviews on the mobile. I think it is because of the <iframe> tag. Any solution for this?

You can check the implementation at
https://staging.casaone.com/products/fortress-sofa-white
Check out the "CasaOne Reviews on Yelp" section at the bottom on the mobile.

**Comment by voronianski** [comment]
@ankit-casaone most likely something is wrong with your code, working example with iframes - https://codesandbox.io/s/1q9pm737ol
