### ISSUE TITLE
Demo Sliding is not working on browser?

### ISSUE THREAD

**Issue by leomyth330** [voronianski/react-swipe#135]
I see sliding is not working for demo page on browser. How can I enable sliding for browser?
Or is this impossible for this library?

**Comment by voronianski** [comment]
this component relies on [Swipe.js](https://github.com/voronianski/swipe-js-iso) which works with `touch` events for swiping. It means swiping will work only on mobile devices, for desktop browsers you need to add custom buttons to control slides.
