### ISSUE TITLE
Use original UI?

### ISSUE THREAD

**Issue by strarsis** [voronianski/react-swipe#137]
Is it possible to use the original swiper UI just by adding the DIVs with classes `swiper-pagination`, `swiper-button-prev`, `swiper-button-next` and `swiper-scrollbar`? The content of `ReactSwipe` component seems to be used purely as slides.

**Comment by voronianski** [comment]
this component is not related to swiper (whatever it is), it's using https://github.com/voronianski/swipe-js-iso under the hood.
