### ISSUE TITLE
Duplicated slides when using two slides

### ISSUE THREAD

**Issue by webeli** [voronianski/react-swipe#142]
## Description
Hi, i noticed a bug in react-swipe that occures when i use two slides.

The amount of slides duplicates everytime there are two slides in place.

This bug makes it hard for me to highlight the current active slide since the index is wrong after it has gone over the second slide...

The image below has **two slides but gets four rendered to the DOM**.

## Image
![image](https://user-images.githubusercontent.com/3446889/43076625-14b4b92a-8e85-11e8-9c01-32d13d0e4222.png)

You can test the bug here, just change the tree slides to two:
http://esnextb.in/?gist=8d9bf6bf17a4a3f779485e4baa6c3f26

**Comment by Mikeks81** [comment]
experiencing the same behavior.   Not that this is the right solution but this issue mentions a similar thing https://github.com/voronianski/react-swipe/issues/129

**Comment by voronianski** [comment]
fixed in Swipe.js - https://github.com/voronianski/swipe-js-iso/commit/7370415ffee049c2a980f86ec5ceb28db7c056c6
