### ISSUE TITLE
Cannot npm/yarn install due to node ^8.0.0 requirement

### ISSUE THREAD

**Issue by hburrows** [voronianski/react-swipe#146]
## Description

I believe the package.json `engine` property was added to 6.0.0; this breaking installation in projects using a new version of node.  If a project is using a version of node other than ^8.0.0 (i.e. like 10.13.0 or anything newer than 8.0) this dependency can no longer be installed.  Maybe you want to switch to using `devEngines` or expressing `engines` as a `>=` (i.e. `>=8.0.0`)

**Comment by voronianski** [comment]
published the update with `>=8.0.0`
