### ISSUE TITLE
Update of swipe-js-iso causes 'window is not defined' error

### ISSUE THREAD

**Issue by kristinalyba** [voronianski/react-swipe#148]
## Description
There is an issue for `swipe-js-iso` repo - https://github.com/voronianski/swipe-js-iso/issues/22 which breaks `react-swipe`. Is it possible to lock the version until `swipe-js-iso` issue is resolved?

**Comment by voronianski** [comment]
@kristinalyba should be fixed in `v6.0.2`

**Comment by voronianski** [comment]
@kristinalyba pls let me know if it's not

**Comment by kristinalyba** [comment]
yeah, it's working, thanks!
