### ISSUE TITLE
Module not found: Can't resolve 'docs/src/modules/components/Pagination'

### ISSUE THREAD

**Issue by renate73** [voronianski/react-swipe#153]
## Demo link

* you can use this link as a boilerplate - 
http://esnextb.in/?gist=8d9bf6bf17a4a3f779485e4baa6c3f26

**Comment by Cyberlane** [comment]
@renate73 I clicked the provided link, I saw some code, but I did not see any errors.
What am I missing? I would be happy to try solve the issue if I can see the error.

**Comment by yysfwls** [comment]
hi,这个问题你解决了吗
