### ISSUE TITLE
Demo doesn't work

### ISSUE THREAD

**Issue by piotr-cz** [voronianski/react-swipe#158]
## Description
[Demo](https://voronianski.github.io/react-swipe/demo/) doesn't work either in touch device or browser emulator

## Demo link
https://voronianski.github.io/react-swipe/demo/

**Comment by Cyberlane** [comment]
@piotr-cz - I just tried it in Chrome Browser emulator, and it works just fine.
I also tried it on my Android phone, and it works just fine.

What issue did you experience?

**Comment by piotr-cz** [comment]
Indeed, it works now on both devices.
I can only recall that at that time it wasn't responding to touch events and only buttons worked.

Thanks for checking.

**Comment by Cyberlane** [comment]
It is completely possible that it was broken, but then got updated between the time that you tried and now. :)

Glad to hear it's solved now.
