### ISSUE TITLE
TypeError when using React: Cannot read property 'firstChild' of undefined

### ISSUE THREAD

**Issue by hulvei3** [voronianski/react-swipe#20]
According to [this post](http://stackoverflow.com/questions/27153166/typeerror-when-using-react-cannot-read-property-firstchild-of-undefined), this can be caused by setting i.e. `react` as a `dependencies` entry in package.json and not as `peerDependencies`.

A work-around is to just remove the react folder within `/node_modules/react-swipe/node_modules/`.
_A more permanent fix is to remove 'react' from `dependencies` in package.json._

**Comment by newenegue** [comment]
@hulvei3 What version of npm are you running?  I've noticed this happening on machines running npm `1.x`, but works fine with npm `2.x`.  I'm not certain if this is the cause/solution.  I still agree that removing `react` from the `dependencies` is the best fix.

**Comment by hulvei3** [comment]
I've reinstall npm completely some time ago. I cant remember what version I was running, but it could have been very old. Now I'm am running 2.7.5 without any problems

**Comment by newenegue** [comment]
I've created a PR for this issue.  Confirmed it works with node 0.10.40/npm 1.4.28

**Comment by voronianski** [comment]
@hulvei3 @newenegue published to npm updated version.

**Comment by hulvei3** [comment]
awesome
