### ISSUE TITLE
Want server-side rendering?

### ISSUE THREAD

**Issue by localnerve** [voronianski/react-swipe#21]
Is this project interested in server-side rendering? I made a [small adjustment](https://github.com/localnerve/react-swipe/blob/master/react-swipe.js) to 2.1.0 that allows it. This improvement cut my speed index in half.

**Comment by jed** [comment]
i think at some point it doesn't make sense to keep building on the original swipe library for something like this, but would love to hear what @voronianski thinks.

**Comment by voronianski** [comment]
@localnerve @jed I think this could be done in separate fork with name like `react-swipe-iso` or smth.

**Comment by jed** [comment]
roger that. thanks for the ping, @localnerve!
