### ISSUE TITLE
slide with multiple elements.

### ISSUE THREAD

**Issue by muralip** [voronianski/react-swipe#22]
I want to integrate slider with multiple element in a single window. Currently we can show only one element at time. Please  help me.

**Comment by nelsieborja** [comment]
+1

**Comment by voronianski** [comment]
@muralip @nelsieborja if there is such limitation then it's related to Swipe.js https://github.com/thebird/swipe/

**Comment by voronianski** [comment]
@muralip @nelsieborja also you can check this component - http://kenwheeler.github.io/nuka-carousel/

**Comment by nelsieborja** [comment]
@voronianski cool thanks!
