### ISSUE TITLE
dynamic content for swipe

### ISSUE THREAD

**Issue by bagadim** [voronianski/react-swipe#23]
Hello,
What I try to make: I have a lot of items to swipe (they can't be splited), and loading all swipe take several seconds, that is very annoying. So I decided to load 3-4 items on init, and then load others if needed while user swipe existing items.

I tried to change `state` on `callback`, it changes, but swipe component doesn't want to rerender with new `state`. I take a look inside `react-swipe` and saw script working with dom directly.

Quesiton: Is it possible to change swipe data dynamically with your component?

**Comment by Wildhoney** [comment]
@bagadim I had the same issue, but then realised why. You need to add the `key` attribute to instruct React that the component needs re-rendering. For the value of `key` it's probably best to use the `images.length` property :+1: :

``` javascript
<ReactSwipe key={images.length}>
    {images}
</ReactSwipe>
```

**Comment by alopes** [comment]
@Wildhoney you just made my day! Thanks

**Comment by Wildhoney** [comment]
Haha &mdash; I remember that feeling when I discovered it was `key`.

**Comment by tlenclos** [comment]
Oh god thanks

**Comment by byronrau** [comment]
thank you! just ran into the same issue!

**Comment by mattlo** [comment]
Also ran into the issue, might be good to add @Wildhoney's solution on the README.

**Comment by Wildhoney** [comment]
Opened a [pull request](https://github.com/jed/react-swipe/pull/48) &mdash; although I'm not entirely convinced my explanation is adequate. Feel free to make suggestions :+1:

**Comment by xturtle** [comment]
useful questions, thanks!

**Comment by vincentsels** [comment]
When the contents (which are other react components) of one of the pages changes, is there a way to re-render only those parts? Should I use some kind of hash of the whole array as key?

**Comment by Wildhoney** [comment]
I've had _some_ success with [`object-hash`](https://github.com/puleos/object-hash) &mdash; although I've noticed it doesn't support `File` objects &mdash; and probably other _special_ objects.

``` javascript
import hash from 'object-hash';

// ...

{ collection.map(model => <li key={ hash(model) }> ... </li>) }
```

Where `li` could quite easily be a React component.

**Comment by vincentsels** [comment]
Thanks @Wildhoney, that indeed does the trick.

**Comment by vincentsels** [comment]
@Wildhoney: however, this re-renders everything (removes and redraws it on the actual DOM), which is not an option in our situation. Only the deepest child component which actually has a change should be re-rendered. Is this possible in some way? It seems such a trivial thing.

**Comment by Wildhoney** [comment]
It would redraw `li` in my example &ndash; which would be your React component. If you want a change deep in your component hierarchy to be reflected in `ReactSwipe` then it _should_ just work. Does your component update just fine outside of the `ReactSwipe` component?

**Comment by vincentsels** [comment]
That's correct: if I just render all the 'pages' without a `<ReactSwipe>` component 'surrounding' them, then the child component with the change does get updated.

This doesn't update (The `render` function of the `<Platform>` doesn't get called):

``` jsx
<ReactSwipe startSlide={startIndex} continuous={true} callback={this.onPlatformSelected} key={this.props.platforms.length}>
    {this.props.platforms.map(platform => <div key={platform.id}><Platform platform={platform} /></div>)}
</ReactSwipe>
```

Whereas his updates just fine:

``` jsx
<div>{this.props.platforms.map(platform => <div key={platform.id}><Platform platform={platform} /></div>)}</div>
```

_Note: I somehow need the additional `div` around the actual `Platform` component/page to get the layout right. Just to make sure that this isn't causing it, I also tested without it - same issue._

_Other note: using `key={hash(platform)}` doesn't work either - also no update._

**Comment by Wildhoney** [comment]
It's because of the `key` on the `ReactSwipe` component &mdash; as soon as React sees that hasn't changed &mdash; because you're only updating an existing `platform` &mdash; then it will merrily move on without diffing the component's `this.props.children`.

Try hashing the array on the `ReactSwipe` component &mdash; I've not tested `object-hash` with an array, so I have no idea if that's possible. Then `object-hash` each child &mdash; if a key for their associated `div` doesn't update then the `Platform` component won't render &mdash; this should **only** update the `Platform` that has changed.

``` html
<ReactSwipe ... key={hash(platforms)}>
  {platforms.map(model => <Platform key={hash(model)} platform={model} />)}
</ReactSwipe>
```

**Comment by vincentsels** [comment]
Instead of only re-rendering the deepest child, that will completely redraw the entire platform - which makes sense I suppose: React thinks it's an entirely different one because it has a different key. Redrawing the entire platform isn't an option in our case because then we lose the scroll position the user was in, it'll jump back to the top.

**Comment by vincentsels** [comment]
Oh my. I've just discovered about the `shouldUpdate` prop, which does exactly what I need. Terribly sorry!!

**Comment by Wildhoney** [comment]
That would also work! No problem. Glad you solved it.

**Comment by maheshambiga** [comment]
It would be a great feature if you could add pagination to the swiper.

**Comment by medJemmoudi** [comment]
Hello folks! is there any way to add more items to ReactSwipe without going back to the first item?

**Comment by rrousselGit** [comment]
@medJemmoudi 
I need to test, but I'm pretty sure you can set swipeOption.startSlide prop to the index you currently are.

**Comment by Richacinas** [comment]
@Wildhoney you sir are the boss. Thanks a lot

**Comment by VyaWave** [comment]
what can i do if i have just 6 children ,but when i change the children deep in the six children ,but it dosen't re-render?i don't want chage the key on the prop ?what the other way to re-render the ReatSwipe?
