### ISSUE TITLE
Desktop Swipe support

### ISSUE THREAD

**Issue by rafaelbiten** [voronianski/react-swipe#30]
Hi! Thanks for this component!

I'm currently using another carousel component on a React project but having a few issues on iOS. I just tried this one and it works GREAT! I just noticed that the swipe is limited to touch devices only. Do you have any plans to add swipe support on desktop too?

Tks!

**Comment by voronianski** [comment]
@rafaelbiten this is not a scope of this component, check - https://github.com/thebird/swipe.
