### ISSUE TITLE
disableSwipe?

### ISSUE THREAD

**Issue by rafaelbiten** [voronianski/react-swipe#33]
edit: found this on the original plugin page that helped me achieve this: https://github.com/thebird/Swipe/issues/391

Tks!

**Comment by voronianski** [comment]
@rafaelbiten ?

**Comment by rafaelbiten** [comment]
Sorry @voronianski , you can close this one. The other 'duplicate' was opened by mistake and I couldn't find where we remove/delete it. Tks!
