### ISSUE TITLE
Support for react-0.14

### ISSUE THREAD

**Issue by seekshiva** [voronianski/react-swipe#35]
`react-swipe` has a hard dependency on react-0.13.3, so I'm unable to update my project to use react-0.14.

Can you suggest a quick-fix for this, until you come up with an upgrade?

**Comment by digitaldavenyc** [comment]
I also have the same issue, a suggestion for a fix or an upgrade would be much appreciated. 

Getting this error:
`Uncaught TypeError: Cannot read property 'firstChild' of undefined`

**Comment by voronianski** [comment]
@seekshiva @digitaldavenyc sorry guys, I will provide new version with react 0.14 support during weekend! Cheers :wine_glass:

**Comment by risto1913** [comment]
looking forward to pulling down the 0.14.x version :)

**Comment by patrick-michelberger** [comment]
waiting for it, too. ;) @voronianski  cheers

**Comment by voronianski** [comment]
added starting from version `3.0.0`.
