### ISSUE TITLE
Next/Prev click delay on Safari - ios 8.1.2

### ISSUE THREAD

**Issue by nvcken** [voronianski/react-swipe#37]
I test on Safari ios 8.1.2
Finger swipe response is good.
But if I click button Next / Prev , it 's take delay time for slide animation.

**Comment by ghost** [comment]
Bit late but still...

This can probable be solved by using fastclick.js in your projects.

"FastClick is a simple, easy-to-use library for eliminating the 300ms delay between a physical tap and the firing of a click event on mobile browsers. "

https://github.com/ftlabs/fastclick

**Comment by voronianski** [comment]
@nvcken @Florisschimandl is right, use FastClick or similar lib.
