### ISSUE TITLE
How to make part of swipe area NOT affect the swipe?

### ISSUE THREAD

**Issue by giantelk** [voronianski/react-swipe#4]
I want to have only the top and bottom of my page allow swiping, so any swipes in the center don't transition. Reason is the middle section will have a game that uses swiping. Top and bottom will be header & footer stuff.

**Comment by voronianski** [comment]
@giantelk put out not swipeable elements out of swipe component and make them speak with one another, it's the clearest solution.

**Comment by giantelk** [comment]
I mean like a section inside the swipe area that itself does not trigger the parent swipe. i.e. I have mobile app with swipe between pages, but on 1 page I want a rectangle area within the main swipe that does not trigger any swipe.
