### ISSUE TITLE
Transition effect

### ISSUE THREAD

**Issue by catalinfeier** [voronianski/react-swipe#40]
Is there any way to add a transition effect for the incoming element? E.g. incoming element enters screen at 70% size and grows to 100% when it reaches the center of the screen (and reverse if the swipe is not completed)?
I am pretty sure there isn't an already implemented solution for transition effects, I am just asking for some ideas/direction for this.

**Comment by voronianski** [comment]
@catalinfeier this is not in scope of this component, pls check [Swipe.js](http://swipejs.com/).
