### ISSUE TITLE
Uncaught Error: Cannot find module "swipe-js-iso"

### ISSUE THREAD

**Issue by justinireland** [voronianski/react-swipe#41]
I'm getting this error "Uncaught Error: Cannot find module "swipe-js-iso" when I try to use this module in my project. I am using React 0.14.

**Comment by voronianski** [comment]
@justinireland what npm version do you use? `swipe-js-iso` is `peerDependency` (https://github.com/jed/react-swipe/blob/gh-pages/package.json#L37) in npm 3+ you need to manually install it by yourself.

**Comment by justinireland** [comment]
I had tried that but I don't think webpack was rebundling it all. Its working now. Thanks.
