### ISSUE TITLE
Non-zero "slideToIndex" while mounting breaks the sync.

### ISSUE THREAD

**Issue by shoaibkalsekar** [voronianski/react-swipe#43]
I wanted to slide to a dynamic index(n) on load/mount. The view displayed the first slide but when I clicked next it moved to n+1 slide. Is this expected? Tweaking the code a bit, I found if the `.slide()` is called inside `componentDidMount` it serves the purpose. But is this advisable? Is this an issue with the swipe library?

**Comment by ash-vd** [comment]
Aren't you supposed to do this using startSlide on the Swipe-node? For example:

```
<Swipe ref="mySwipe" startSlide={2}>
    {swipeContainers}
</Swipe>
```

This works for me...

**Comment by voronianski** [comment]
@shoaibkalsekar use `startSlide` as @ashwinvandijk suggests.
