### ISSUE TITLE
Not possible to have render different swipers in the same container

### ISSUE THREAD

**Issue by vongohren** [voronianski/react-swipe#51]
https://github.com/jed/react-swipe/pull/50

**Comment by vongohren** [comment]
@voronianski @jed would it be possible with a comment on this?

**Comment by voronianski** [comment]
@Snorlock that's fine, just check the comments.

**Comment by voronianski** [comment]
@Snorlock also please check this PR - https://github.com/jed/react-swipe/pull/28 aren't you trying to address something similar?

**Comment by voronianski** [comment]
@Snorlock and also this one - https://github.com/jed/react-swipe/pull/15

**Comment by voronianski** [comment]
/cc @oc-shady @wanglam @dazld @vitalyrotari

Please guys, could you coordinate on this issue, as it looks similar to your previous suggestions - https://github.com/jed/react-swipe/pull/28, https://github.com/jed/react-swipe/pull/15

**Comment by voronianski** [comment]
@Snorlock also did you check https://github.com/voronianski/react-swipe#re-rendering?

**Comment by vongohren** [comment]
@voronianski one problem with basing the rerendering on images lenght is that you have to have different length on the swiper to rerender. What if you have a new swiper that has the same amount of pictures? It failes I guess?

**Comment by vongohren** [comment]
#28 is also only based on length, and dont know if setup will do the deed here?
#15 looks overly complicated to get the issue done

**Comment by voronianski** [comment]
@Snorlock 

> #15 looks overly complicated to get the issue done

agree

Regarding your solution - maybe it's worth insread of calling `new Swipe` to call `this.swipe.setup()`?

**Comment by vongohren** [comment]
But how does the swiper know of new properties when you call this.swipe setup? Im open for it but dont know how that should work? @voronianski

**Comment by voronianski** [comment]
@Snorlock could you share your example? Why do you need need new props, as I understand you just need to rerender slider with new images?

**Comment by vongohren** [comment]
No your acctually right. Setup works for me, and acctually solves the problem I just raised. But continouous is not kept across setups for some reason?

**Comment by vongohren** [comment]
Or its kept across state, but when changing to an slider with lenght less than to its set to false and that makes the continius stay false for the rest of the changing.

**Comment by vongohren** [comment]
If I do this:

```
        this.swipe.kill();
        delete this.swipe;
        this.swipe = Swipe(ReactDOM.findDOMNode(this), objectAssign({}, this.props));
```

It keeps continuous and there is no listener bugs. So what you think?

**Comment by voronianski** [comment]
@Snorlock that's fine, except there's no need to `delete this.swipe`.

**Comment by voronianski** [comment]
@Snorlock and also prop should be renamed imho.

**Comment by vongohren** [comment]
@voronianski its all done in the PR now
