### ISSUE TITLE
IE9

### ISSUE THREAD

**Issue by holloway** [voronianski/react-swipe#52]
Your current demo HTML has this downgrade tag,

  &lt;meta http-equiv="X-UA-Compatible" content="IE=8"&gt;

Which forces IE9 to use an IE8 engine and then nothing works.

Changing this to,

  &lt;meta http-equiv="X-UA-Compatible" content="IE=Edge" /&gt;

Will make it work just fine in IE9.

**Comment by voronianski** [comment]
@holloway thanks!
