### ISSUE TITLE
Callback is called 3 times when changing direction

### ISSUE THREAD

**Issue by vongohren** [voronianski/react-swipe#54]
This might not have to be anything to do with this component, but i wonder if you have experienced it or have a better way of working with the callback.
For some reason when I work with actual swiping the callback is called 3 times and this screws up what card is show when I set state in the callback. Have you ever experienced this?

```
    callback: function(index) {
        this.props.setNewState(index);
    },
```

**Comment by voronianski** [comment]
@Snorlock never used it, the right place for your question will be - https://github.com/thebird/swipe

**Comment by vongohren** [comment]
I think its a "collaboration" between react and new Object. Because as I mentioned not newin up the swiper fixed the double callback

**Comment by voronianski** [comment]
@Snorlock pls check console in this example - http://voronianski.github.io/react-swipe/demo/?continuous=true, looks like `callback` is fired correctly.
