### ISSUE TITLE
Swiping is broken when it is two slides?

### ISSUE THREAD

**Issue by vongohren** [voronianski/react-swipe#55]
Have you ever tried two slides? I just got a case where I have two slides and it duplicates and breaks.
It seems to be broken because of these lines

```
      //special case if two slides
      if (browser.transitions && options.continuous && slides.length < 3) {
        element.appendChild(slides[0].cloneNode(true));
        element.appendChild(element.children[1].cloneNode(true));
        slides = element.children;
      }
```

**Comment by voronianski** [comment]
@Snorlock nope, where are these lines from?

**Comment by vongohren** [comment]
@voronianski its from the https://github.com/thebird/swipe. But i think it might be a special case when wrapped in react, because these lines are quite old. https://github.com/thebird/Swipe/blob/master/swipe.js#L47

Special case if continuous

**Comment by alonbardavid** [comment]
We've also experienced this, what we've done currently is to clone from 2 to 4 by ourselves if the children is only 2.
That's not a nice solution though.

**Comment by voronianski** [comment]
@Snorlock @Illniyar please update issue regarding https://github.com/voronianski/react-swipe/blob/gh-pages/.github/ISSUE_TEMPLATE.md and feel free to reopen it then.

**Comment by vongohren** [comment]
What do you mean? You want me to create a jfiddle for this?

**Comment by voronianski** [comment]
@Snorlock it works now, pls check demo http://voronianski.github.io/react-swipe/demo/?continuous=true&slidesNum=2
