### ISSUE TITLE
How can I continue swipe when I swipe to last slide with endpoints?

### ISSUE THREAD

**Issue by Tinple** [voronianski/react-swipe#57]
Say I want to create a welcome page on mobile, when I swipe to the last image(`welcome3.jpg`), I want my next swipe to a new page, but because of the endpoints(`continuous={false}`), I can't start my next swipe when I swipe to the last image, any helps? Or is `react-swipe` meet this situation?

``` javascript
<ReactSwipe
  continuous={false}
  transitionEnd={this.transitionEnd}
>
  <img src="welcome1.jpg" alt=""/>
  <img src="welcome2.jpg" alt=""/>
  <img src="welcome3.jpg" alt=""/>
</ReactSwipe>
```

**Comment by andrzey** [comment]
can't you just set continous to true? If you want to show welcome1 after welcome3 I mean.

**Comment by Tinple** [comment]
Actually, I don't want to set continous to true. If that, user can swipe to welcome3 from welcome1, which is not my desire. @andrzey
