### ISSUE TITLE
Lazy loading images

### ISSUE THREAD

**Issue by psugihara** [voronianski/react-swipe#58]
Is there a recommended method for lazy loading images?

**Comment by zengxiaoluan** [comment]
支持图片懒加载的方式：`transitionEnd(index, elem){

    this.loadImages($(elem).find('img'))

}`

**Comment by emwee** [comment]
You could use a `data-src` attribute for all images that are not immediately loaded, and then use the 'callback' callback function to load the image. I use something like this:

```
<ReactSwipe
  swipeOptions={{
    callback: (index, el) => {
      const image = el.querySelector("img");
      const { src, isLoaded } = image.dataset;
      const shouldloadImage = !!!isLoaded && src;

      if (shouldloadImage) {
        image.setAttribute("src", src);
        image.setAttribute("data-is-loaded", true);
      }
    }
  }}
>
```
