### ISSUE TITLE
Can't get next() working.

### ISSUE THREAD

**Issue by giantelk** [voronianski/react-swipe#6]
I'm trying to modify swipe.js to support next/prev, but can't figure out how to call this.swipe.next() in render(). Any ideas?

**Comment by giantelk** [comment]
Also see here, this links to a JSFiddle with some changes to your swipe.js file. I'm trying to get it working but it's just not there yet. I got part way there, putting this.swipe in this.state. Although weird thing, when I did that, I was also able to access `this.swipe.next()` from render(), as well as `this.state.mySwipe.next()`. Not sure why ReactJS let that happen. See code below:

http://stackoverflow.com/questions/27085523/react-swipe-api-invariant-violation-w-reactjs

**Comment by voronianski** [comment]
@giantelk there is a prop `slideToIndex` now - https://github.com/jed/react-swipe#props, with its' help you are free to implement `next/prev` methods yourself - just re-render the parent component which contains `ReactSwipe` and it will slide to provided index.

**Comment by vincentsels** [comment]
@voronianski : I don't see this option/prop in the code and it's not documented? Is there an other solution now?
