### ISSUE TITLE
`shouldUpdate` dont work

### ISSUE THREAD

**Issue by KODerFunk** [voronianski/react-swipe#64]
`shouldUpdate` dont work. Cant disable update by return `false`, because in `shouldComponentUpdate` used `or` condition after calling `shouldUpdate` where `(nextProps.children!==this.props.children)` always be `true`.
Use local copy of component with equaling `children.length`.
Also `componentWillReceiveProps` always reinit Swiper ((( also patched localy.

**Comment by voronianski** [comment]
@KODerFunk sorry, it was introduced here - https://github.com/voronianski/react-swipe/pull/15 I can easily revert it, but I think it's better to discuss this once again, guys @holloway @wanglam @vitalyrotari take a look please.

**Comment by voronianski** [comment]
@Snorlock maybe it's also related to https://github.com/voronianski/react-swipe/issues/51

**Comment by voronianski** [comment]
@KODerFunk please update issue regarding https://github.com/voronianski/react-swipe/blob/gh-pages/.github/ISSUE_TEMPLATE.md and feel free to reopen it then.

**Comment by voronianski** [comment]
@KODerFunk `v5.0.0` has breaking change, there's no `shouldUpdate` prop anymore.
