### ISSUE TITLE
Need starter code-template for issues

### ISSUE THREAD

**Issue by KODerFunk** [voronianski/react-swipe#66]
## Describtion

Issue template its cool, but not enough. Please, make valid template with `react-swipe` usage.
I realy hard try connect code, but problem is deeper.
## Demo link

For example, my third and best try: https://jsbin.com/dedobazoli/1/edit?html,css,js,output

**Comment by voronianski** [comment]
@KODerFunk check this link - http://esnextb.in/?gist=8d9bf6bf17a4a3f779485e4baa6c3f26
