### ISSUE TITLE
Vertical displacement parent disabled

### ISSUE THREAD

**Issue by saidmoya12** [voronianski/react-swipe#69]
The vertical displacement is unsupported on mobile devices.

is possible improve a prop to enable this?

**Comment by voronianski** [comment]
@saidmoya12 do you mean vertical swiping?

**Comment by rohanprasad** [comment]
@voronianski Does this support vertical swiping?

**Comment by voronianski** [comment]
@rohanprasad I've never tried to make it work, but it depends if [Swipe.js](https://github.com/voronianski/swipe-js-iso) supports vertical swiping. I assume it's just a matter of custom CSS for slider.
