### ISSUE TITLE
Next/prev buttons over the swipable area

### ISSUE THREAD

**Issue by ssuvorov** [voronianski/react-swipe#71]
Hey,
I tried to add next/prev arrows out of `Swipe` tag, Positioned them with css on top of swipable area. If you try to start swiping from arrows - it not possible. Of course, swipe is only available when over images there are no external tags with higher `z-index`.

Is it possible to extend component with arrows (add additional property in config to toggle their visibility)?
...and continue use swipe even if you start the action from red area?
<img width="600" alt="screen shot 2016-04-07 at 15 22 51" src="https://cloud.githubusercontent.com/assets/3448821/14352430/d0429a4e-fcd4-11e5-9095-6c9c3b64e6aa.png">

**Comment by voronianski** [comment]
@ssuvorov Did you try to style images with less width & height?
<img width="600" alt="d0429a4e-fcd4-11e5-9095-6c9c3b64e6aa" src="https://cloud.githubusercontent.com/assets/974035/14353740/1e4e38b6-fce3-11e5-9117-2d6bc5904a9b.png">

This way they will overlap with minimum swiping area.

**Comment by ssuvorov** [comment]
This will be our solution if it's not possible :) Of we'll decrease only width or even just hide them at all. 
Anyway it might be cool if you can tap on left/right side and the image will be changed.

**Comment by voronianski** [comment]
@ssuvorov I will think about it, maybe there will be better solution :)

**Comment by ssuvorov** [comment]
Yes, also there are many additional components that could be added - price, dots, image's counter, etc. Each of them deny clicking. 
The solution can be filtering out only swipable items. Or put a div over them all.

**Comment by voronianski** [comment]
@ssuvorov I don't think that this should be done inside this component. It sounds more like `react-swipe-gallery` - a component on top of `react-swipe` :)

**Comment by ssuvorov** [comment]
@voronianski sure, they will be define out of it, but in this plugin I guess it should be like:

``` diff
<div ref="container" id={id} className={`react-swipe-container ${className}`} style={style.container}>
+ children.price
+ children.arrows
+ others children that aren't swipable

  <div style={style.wrapper}>
+ Apply transform while swiping only for the rest of the children. Here
    {React.Children.map(children, child => {
        return React.cloneElement(child, {style: style.child});
    })}
  </div>
</div>
```

**Comment by voronianski** [comment]
@ssuvorov btw did you check http://kenwheeler.github.io/nuka-carousel/ ?

**Comment by ssuvorov** [comment]
@voronianski I had no time to change the lib, but anyway I will try one day. Need to solve everything with you lib first :)

**Comment by qiaolevip** [comment]
It's possible to add extra overlaid on the ReactSwipe Component

```
.bullets-container {
    position: absolute;
    left: 0;
    right: 0;
    text-align: center;
    bottom: 8px;
    font-size: 0;
    z-index: 2;
}
```

![screenshot from 2016-08-03 14-58-16](https://cloud.githubusercontent.com/assets/996755/17356679/64339b64-598b-11e6-9dbc-8f0b1d6e578d.png)
