### ISSUE TITLE
children in react-swipe display in the wrong position

### ISSUE THREAD

**Issue by liz282907** [voronianski/react-swipe#75]
## Description

i'm using the react swipe for my application,suppose there are 4 children in ReactSwipe component,each one has a with of 300px,however, when i debug my project on chrome, i found that the whole height is 300*4,and the second one is on the position of (300,300), just like in the diagonal line. can anyone point out where the problem is ?
## screenshot link

![](http://7xrn7f.com1.z0.glb.clouddn.com/16-6-10/93809598.jpg)

**Comment by Mr-Taco** [comment]
i am experiencing the same issue. all slides after the first are pushed down 100% of their height \* slide number, so you do not see slides after the first one.

**Comment by Mr-Taco** [comment]
i added "float: left; position: relative;" to each slide to fix this.
