### ISSUE TITLE
recalculate on componentDidUpdate?

### ISSUE THREAD

**Issue by ghost23** [voronianski/react-swipe#77]
Hi,

swipe.js supports to recalculate dimensions and positions via another call to setup(), if anything in the DOM changes, that makes it necessary.

Could react-swipe support that via something like:

`componentDidUpdate() {
   this.swipe.setup();
}`

?

**Comment by voronianski** [comment]
@ghost23 you can make setup in your component which uses react-swipe:

``` js
componentDidUpdate() { 
  this.refs.yourSwipeRef.swipe.setup(); 
}
```
