### ISSUE TITLE
Swiper takes some time to get initialized

### ISSUE THREAD

**Issue by maheshambiga** [voronianski/react-swipe#78]
When page loads, swiper is not initialized and displayed immediately but it takes about 2-3 secs to load.

**Comment by qiaolevip** [comment]
Yes, seem issue in my project complain with many people is not just delay also have big times not show images.
And I deal with this code do a test , I hope it work

```
items && items.length > 0 ?
        <div className="slider-container">
          <ReactSwipe className={className} swipeOptions={{speed: 400, auto: 3000, callback: this.attractBullet.bind(this)}}>
            {
              items.map((item, i) =>
                <div key={i}>
                  <img src={item} />
                </div>
              )
            }
          </ReactSwipe>
          <Bullets size={items.length} curIndex={curIndex} />
        </div> : null
```

**Comment by voronianski** [comment]
@maheshambiga @qiaolevip I think it's nothing related to the react-swipe if your images take some time to load. You will need to implement some kind of preloader for your images or cache them properly.
