### ISSUE TITLE
Demo Code not working

### ISSUE THREAD

**Issue by KeKs0r** [voronianski/react-swipe#8]
Hi,

I am slightly unsure why but the Demo Code is not working for me.

One of the things that is somehow weird is this line:
`var carousel = Swipe({id: "mySwipe"}, panes)`

Because it actually renders "mySwipe" into the page and does not apply it as ID. And I think this is only for styling all the other entries, but when I render the carousel, I always see all 20 entries and the css which should "hide" them is not applied. I am not sure if this is related to the mySwipe problem, but I thought it isn't.

It might be related to swipe / react versions.

**Comment by voronianski** [comment]
@KeKs0r updated react and demo.
