### ISSUE TITLE
next() & prev() refs reactSwipe shows undefined

### ISSUE THREAD

**Issue by phtn** [voronianski/react-swipe#81]
## reactSwipe as undefined

I'm using Meteor as a framework. Swiping works great!
But I cant seem to figure out the next() & prev() buttons to work. 

`next() {   this.refs.reactSwipe.next() }`

Is there a way to trigger next() & prev() without using 

> refs

**Comment by Mehdimaker** [comment]
+1

**Comment by qiaolevip** [comment]
There have a method to operate with ReactSwipe use js:

```
// In source code provides ReactSwipe.propTypes id: _react.PropTypes.string property
// Then define: 
<ReactSwipe id="reactSwipe" swipeOptions=..... />

// When you need go next() or prev()
document.getElementById('reactSwipe').prev();
// or
document.getElementById('reactSwipe').next();
```

or Other Swipe.js provides methods

Swipe API

Swipe exposes a few functions that can be useful for script control of your slider.

prev() slide to prev

next() slide to next

getPos() returns current slide index position

getNumSlides() returns the total amount of slides

slide(index, duration) slide to set index position (duration: speed of transition in milliseconds)

**Comment by voronianski** [comment]
@phtn @Mehdimaker @qiaolevip why refs to ReactSwipe do no work? see - https://github.com/voronianski/react-swipe/blob/gh-pages/src/reactSwipe.js#L60

**Comment by Mehdimaker** [comment]
it works now !
i have forgot to bind my function:
onClick={this.next.bind(this)}
