### ISSUE TITLE
Uncaught TypeError: (0 , _swipeJsIso2.default) is not a function

### ISSUE THREAD

**Issue by WangJintong** [voronianski/react-swipe#82]
## Description

react-swipe.js:95 Uncaught TypeError: (0 , _swipeJsIso2.default) is not a functioncomponentDidMount @ react-swipe.js:95invokeComponentDidMountWithTimer @ react.js:5735notifyAll @ react.js:840close @ react.js:13341closeAll @ react.js:16734perform @ react.js:16681batchedMountComponentIntoNode @ react.js:11717perform @ react.js:16668batchedUpdates @ react.js:10161batchedUpdates @ react.js:14385_renderNewRootComponent @ react.js:11876_renderSubtreeIntoContainer @ react.js:11962render @ react.js:11983(anonymous function) @ app.js:29
## Demo link
- you can use this link as a boilerplate - 
  http://esnextb.in/?gist=8d9bf6bf17a4a3f779485e4baa6c3f26

**Comment by voronianski** [comment]
@WangJintong could you provide more info? As for the first sight it looks like there is no `swipe-js-iso` or setup of babel is not correct.

**Comment by voronianski** [comment]
@WangJintong pls check:
- http://stackoverflow.com/questions/33505992/babel-6-changes-how-it-exports-default
- https://www.npmjs.com/package/babel-plugin-add-module-exports

**Comment by WangJintong** [comment]
@voronianski : 
kevin@kevin-6531s:~/react-world/method_babel-cli$ npm ls | grep swipe
├── react-swipe@5.0.3
└── swipe-js-iso@2.0.3
package.json like this:
{
  "scripts": {
    "babel": "babel src --out-dir build -w",
    "server": "browser-sync --port 4000 start --server --files \"**/*.html\" \"**/_.css\" \"build/__/_.js\" "
  },
  "babel": {
    "presets": [
      "es2015",
      "react"
    ],
    "sourceMaps": false
  },
  "dependencies": {
    "react": "^15.2.1",
    "react-dom": "^15.2.1",
    "react-swipe": "^5.0.3",
    "swipe-js-iso": "^2.0.3"
  },
  "devDependencies": {
    "babel-cli": "^6.11.4",
    "babel-preset-es2015": "^6.9.0",
    "babel-preset-react": "^6.11.1",
    "babel-preset-stage-0": "^6.5.0",
    "browser-sync": "^2.13.0"
  }
}
app.js:
const Carousel = React.createClass({
    render: function() {
        return (
            <ReactSwipe className="carousel" swipeOptions={{continuous: false}}
                <divPANE 1</div
                <divPANE 2</div
                <divPANE 3</div
            </ReactSwipe
        );
    }
});

ReactDOM.render( <Carousel/> , document.getElementById('app'));

commond is : npm run babel  &  npm run server

Help me ,thanks..

**Comment by huangbinjie** [comment]
it seem babel compile code: `module.exports = exports['default'];` conflict with webpack's module, remove this line, it working

**Comment by WangJintong** [comment]
@huangbinjie thanks. I try to reimplement demo based on webpack, it works ok.
