### ISSUE TITLE
Swipe is not working in windows surface tablet.

### ISSUE THREAD

**Issue by rajeshwar-peel** [voronianski/react-swipe#83]
## Description

I am using this plugin with React JS for windows mobile and desktop application In mobile, i am able to swipe the sliders, but in windows surface tablet the swipe is not working. Could you please suggest a resolution for this issue?
## Demo link
- you can use this link as a boilerplate - 
  http://esnextb.in/?gist=8d9bf6bf17a4a3f779485e4baa6c3f26

**Comment by voronianski** [comment]
@rajeshwar-peel sorry, I don't have device to repro it and your issue doesn't have enough info. If there will be more issues related or you provide the detailed info (error or smth) then we can reopen it.
