### ISSUE TITLE
disableScroll value not being set

### ISSUE THREAD

**Issue by anmolg** [voronianski/react-swipe#84]
## Description

Opening a ReactSwipe container with the following attributes:

`<ReactSwipe className="carousel" ref="reactSwipe"  swipeOptions={{disableScroll : true, continuous : false}}>`

Continuous is being recognized as false, but disableScroll is not being recognized as true. Could someone confirm how I should make it so that you cannot swipe through touching?

**Comment by voronianski** [comment]
@anmolg it looks like a problem of Swipe.js library.
