### ISSUE TITLE
Support for multiple slides

### ISSUE THREAD

**Issue by nelsieborja** [voronianski/react-swipe#85]
This is the best React Slider I've seen so far and I would really want to use it on my project but the problem is it doesnt support multiple slides. Will you be able to support it soon?

**Comment by voronianski** [comment]
@nelsieborja what do you mean by multiple slides?

**Comment by nelsieborja** [comment]
@voronianski thank you for your quick response. I meant 2 or more slides to be visible at a time?

**Comment by voronianski** [comment]
@nelsieborja check [Swipe.js docs](https://github.com/voronianski/swipe-js-iso), maybe it's possible but I'm not sure. At least this component is just a thin component wrapper around it.
