### ISSUE TITLE
Version 5.0.4 seems to be broken

### ISSUE THREAD

**Issue by GuillaumeSalles** [voronianski/react-swipe#86]
Hi,

I get the error : "Cannot find module "react-swipe"" with the version 5.0.4.

I had to fix the version of react-swipe to 5.0.3 to make my app work again.

Thanks for your work !

**Comment by phaistonian** [comment]
Same issue here.

**Comment by adityasaxena** [comment]
same issue here.
`react-swipe module not found`

We're setting ourselves back to 5.0.3 meanwhile

**Comment by voronianski** [comment]
@GuillaumeSalles  @phaistonian  @adityasaxena  https://www.npmjs.com/package/react-swipe - 5.0.4 is the latest of 30 releases

**Comment by johanforssell** [comment]
`5.0.4` is missing its `index.js` file - it's not usable. Must be the old npm bug where it's not generated

**Comment by voronianski** [comment]
@johanforssell should be fixed in `5.0.5`.
