### ISSUE TITLE
Question: change route/url after swipe without re-render

### ISSUE THREAD

**Issue by vincentsels** [voronianski/react-swipe#87]
This isn't an issue, rather a question: I want the currently active pane to be reflected in my app's active route. Think of something like /images/1 where the '1' changes to 2 when someone swipes to the next image, etc. 

How can I achieve this without the animation and rendering to re-occur?
- When I update the route in the `callback` handler, it results in a lot of duplicate execution resulting in a long frame. 
- When I update the route in the `transitionEnd` handler, the performance is fine, but after the new pane is selected, the swipe animation occurs a second time.

I searched whether it's possible to just update the route without a state transition in react-router, but that doesn't seem to be supported. Using `window.history.pushState` seems to work at first sight, but as soon as react reads its route and re-renders anything based on it, it will use whatever was set previously...

Note that the stuff I'm rendering inside the panes is based on data passed in as a prop and changes frequently, upon which the pane (contents) must be re-rendered.

**Comment by vincentsels** [comment]
I was using v4. In v5 this seems to be fixed when using `transitionEnd´. I assume there's an internal check whether the new and active slide are the same and if they are, no animation is displayed.

**Comment by joshwcomeau** [comment]
Note that with React Router v4, this should be pretty simple to accomplish :) you would just set `<Route> components within the slides being swiped.

Happy to elaborate if anyone's curious.
