### ISSUE TITLE
How to use slideToIndex

### ISSUE THREAD

**Issue by NgKhanh** [voronianski/react-swipe#89]
How to use **slideToIndex** on right way ?

`<ReactSwipe  slideToIndex={this.state.curTab} >`
or
`<ReactSwipe  swipeOptions={{slideToIndex:this.state.curTab}} >`

Now nothing work for me.  Pls help!

**Comment by voronianski** [comment]
@khacthanh there is no `slideToIndex` option anymore, pls use swipeOptions' `startSlide` property - `<ReactSwipe swipeOptions={{startSlide: this.state.curTab}} >`. Example:
- https://github.com/voronianski/react-swipe/blob/gh-pages/demo/index.js#L21
- http://voronianski.github.io/react-swipe/demo/?continuous=true&startSlide=2
