### ISSUE TITLE
How to set up options can make swipe automatic ?

### ISSUE THREAD

**Issue by JourneyL** [voronianski/react-swipe#93]
## Demo link

* you can use this link as a boilerplate - 
http://esnextb.in/?gist=8d9bf6bf17a4a3f779485e4baa6c3f26

**Comment by voronianski** [comment]
https://github.com/voronianski/swipe-js-iso#config-options `auto` option, example - http://voronianski.github.io/react-swipe/demo/?continuous=true&auto=1000.
