### ISSUE TITLE
Cannot make it work after last update ?

### ISSUE THREAD

**Issue by stephanemartinw** [voronianski/react-swipe#95]
Hello, 

I cannot make swipe work, since (?) I've updated the component yesterday ? Display is ok, no console error, but no swipe.
Is it possible that somme goes wrong in this new version ?
Thank you for your help,

Stephane

**Comment by voronianski** [comment]
@stephanemartinw what version are you using?

**Comment by voronianski** [comment]
@stephanemartinw also it will be helpful if you'll share a bit of code.

**Comment by stephanemartinw** [comment]
Hello, 

I use 3.9.2, in a very simple test code :



Thank you for your quick answer,


Stéphane Martin
--
> @stephanemartinw > designer et développeur web freelance >  +33 (0)9 70 44 98 47 / +33 (0)7 83 44 80 15 > www.stephanemartinw.com > contact@stephanemartinw.com

**Comment by voronianski** [comment]
@stephanemartinw there are no such version of react-swipe https://github.com/voronianski/react-swipe/releases

**Comment by stephanemartinw** [comment]
Sorry, 3.9.2 was the npm -v display.
Use version is 5.0.6.

Thank you.


Stéphane Martin
--
> @stephanemartinw > designer et développeur web freelance >  +33 (0)9 70 44 98 47 / +33 (0)7 83 44 80 15 > www.stephanemartinw.com > contact@stephanemartinw.com

**Comment by stephanemartinw** [comment]
Hello, 

Finally, the point was that you cannot write this : 

<ReactSwipe>
	<MyComponent></MyComponent>
</ReactSwipe>



You have to write : 
<MyComponent style={props.style}>
</MyComponent>

I’m a react beginner, but maybe this point could be added to documentation ?

Best regards,



Stéphane Martin
--
> @stephanemartinw > designer et développeur web freelance >  +33 (0)9 70 44 98 47 / +33 (0)7 83 44 80 15 > www.stephanemartinw.com > contact@stephanemartinw.com

**Comment by voronianski** [comment]
@stephanemartinw what is `props.style`?
