### ISSUE TITLE
Multiple panels in view at once? (question, not bug!)

### ISSUE THREAD

**Issue by Ganasist** [voronianski/react-swipe#96]
## Description
I'd like to setup this great component on desktop / tablet to display 3 panels at once, center one is 'focus'. It was easy to do single panel swiping (i.e. mobile), but I'm having trouble adjusting the props / styles for react-swipe in order to achieve my desired effect on larger screens. Any help you can provide would be much appreciated. I've also posted this question on Stackoverflow. See attached image example.

## Demo link
<img width="557" alt="screen shot 2016-12-02 at 14 32 39" src="https://cloud.githubusercontent.com/assets/2892647/20835864/0a132e3a-b89d-11e6-9f66-b148d0bc7776.png">

* you can use this link as a boilerplate - 
http://esnextb.in/?gist=8d9bf6bf17a4a3f779485e4baa6c3f26

**Comment by voronianski** [comment]
@Ganasist sorry, I'm not sure that it's possible to achieve such effect with Swipe.js, but you can try to edit items with css.
