### ISSUE TITLE
How to set this config of 'slidesPerView' in react-swipe?

### ISSUE THREAD

**Issue by wd2010** [voronianski/react-swipe#97]
I want to set the swipe to show 3 views, but there have no this config,such as 'slidesPerView' in swiperjs,how can i do? http://www.swiper.com.cn/api/Slides_grid/2014/1217/50.html

**Comment by voronianski** [comment]
@wd2010 react-swipe is a wrapper around SwipeJS - https://github.com/thebird/swipe/ and there is no such option for that case.
