### ISSUE TITLE
Initial item width doesn't look optimal (right offset?)

### ISSUE THREAD

**Issue by JimVercoelen** [voronianski/react-swipe#98]
This issue is about the initial width of an item.

If you look at the [demo](http://voronianski.github.io/react-swipe/demo/) the width has an right offset which disappears after page resizing.

I'am facing this problem myself and can't figure out how to work around this.

Is this known? Is there a solution?

**Comment by Richacinas** [comment]
I'm facing exactly the same problem

**Comment by tamirchuba** [comment]
I have faced same problem and tried to fix it by setting wrapper element's width by exact size of window (I mean not 100%, by window's width points). This time initial width of items are shown correctly, but it destroys layout after resizing.

**Comment by poorbug** [comment]
```
<div style={{ width: '100vw' }}>
  <Swipe {...someProps}/>
</div>
```

That works.

**Comment by voronianski** [comment]
@JimVercoelen @tamirchuba @Richacinas @poorbug closing this as not related to this module, if there's an issue it should be fixed in Swipe.js module.
