### ISSUE TITLE
css transform on every element causing browser crash

### ISSUE THREAD

**Issue by tadjohnston** [voronianski/react-swipe#99]
## Description

A large amount of images (say 30-40) causes a crash each time in iOS Safari.  This is due to the fact that this is putting a `transform` on every single image is causing a separate layer render for each one of the images thus increasing GPU load and running out of memory.

Unfortunately there is no way to remove the transform because of the way the `objectAssign` is written here.

```
style: child.props.style ? objectAssign(child.props.style, style.child) : style.child
```
https://github.com/voronianski/react-swipe/blob/gh-pages/src/reactSwipe.js#L90

## Steps to Reproduce

Generate 40 images (can even be the same image) and load this on Safari iOS. This was tested on an iPhone 6+.

If any more information is needed, please let me know.

**Comment by STRML** [comment]
The correct solution would be to always override property with `child.props.style` - if the developer has provided a style he/she reasonably expects it to override builtins.

Additionally, the above code is actually mutating `child.props.style`.

The fix:

```js
style: child.props.style ? objectAssign({}, style.child, child.props.style) : style.child
```

**Comment by voronianski** [comment]
@STRML @tadjohnston please check the latest version `5.0.7`, should be fixed.
